export const projects = [
  {
    title: 'NFT-Marketplace Clone',
    description: "It is a nft marketplace clone running on api of OpenSea testnet , which display NFT collections.",
    image: '/images/marketplace.png',
    tags: ['JavaScript', 'Axios', 'React'],
    source: 'https://github.com/BhumilModi/NFT-Marketplace-Clone',
    visit: 'https://github.com/BhumilModi/NFT-Marketplace-Clone',
    id: 0,
  },
  {
    title: 'Music-App Website',
    description: "This is a static website landing page for music app, made with react and Framer-Motion.",
    image: '/images/music-app.png',
    tags: ['React', 'JavaScript', 'Tailwind', 'Framer-Motion'],
    source: 'https://github.com/BhumilModi/Music-App',
    visit: 'https://music-app-bhumil.vercel.app/',
    id: 1,
  },
  {
    title: 'Twiiter-Web3-clone',
    description: "It is static frontend clone of twitter app , made with metamask authenification.",
    image: '/images/twitter.png',
    tags: ['React', 'JavaScript', 'Next.js', 'Tailwind', 'Metamask'],
    source: 'https://github.com/BhumilModi/nextjs-course-app',
    visit: 'https://github.com/BhumilModi/nextjs-course-app',
    id: 2,
  },
  {
    title: 'GPT3-Clone',
    description: "This is a static website made wiht the help of a Figma design , made as a practice to learn React.",
    image: '/images/gpt3-clone.png',
    tags: ['React', 'JavaScript', 'CSS3'],
    source: 'https://github.com/BhumilModi/GPT3-clone',
    visit: 'https://gpt3-clone.vercel.app/',
    id: 3,
  },
  {
    title: 'Rock-Paper-Scissors Game',
    description: "This is a Simple 2 player game made with React , it is one of the project which is designed and made completely from scratch by me , Also it is live at vercel.",
    image: '/images/rock-paper-scissors.png',
    tags: ['React', 'JavaScript', 'CSS5'],
    source: 'https://github.com/BhumilModi/Rock-Paper-Scissor-Game',
    visit: 'https://rock-paper-scissor-game-nine.vercel.app/',
    id: 4,
  },
  {
    title: 'Todo-List',
    description: "This is one the most basic project which everyone tries while learning Javascript , it is smile todo-list app made while I started doing Javascript and CSS.",
    image: '/images/todo-list.png',
    tags: ['HTML5', 'JavaScript', 'CSS3'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started My Journey as CSE student.', },
  { year: 2020, text: 'Got introduced to Front-end Development as a College project', },
  { year: 2021, text: 'Started Learning Deep Concepts of Front-End Development', },
  { year: 2022, text: 'Started Working on some Real Projects as a Front-End Developer', },
];