export const projects = [
  {
    title: 'Memorize',
    description: "This is full-stack photo gallery web app which is clone of pinterest.",
    image: '/images/rock-paper-scissors.png',
    tags: ['React', 'JavaScript', 'Tailwind', 'Sanity'],
    source: 'https://github.com/BhumilModi/Memorize',
    visit: 'https://memorize-photo-app.vercel.app/',
    id: 0,
  },
  {
    title: 'weNotes',
    description: "A static website for a Notes Selling app , based on web3.0 with metamask authentification.",
    image: '/images/weNotes.png',
    tags: ['Next.Js', 'JavaScript', 'Tailwind', 'Metamask'],
    source: 'https://github.com/BhumilModi/WEnotes-Marketplace',
    visit: 'https://we-notes-marketplace.vercel.app/',
    id: 1,
  },
  {
    title: 'NFT-Marketplace Clone',
    description: "It is a nft marketplace clone running on api of OpenSea testnet , which display NFT collections.",
    image: '/images/marketplace.png',
    tags: ['JavaScript', 'Axios', 'React'],
    source: 'https://github.com/BhumilModi/NFT-Marketplace-Clone',
    visit: 'https://github.com/BhumilModi/NFT-Marketplace-Clone',
    id: 2,
  },
  {
    title: 'Music-App Website',
    description: "This is a static website landing page for music app, made with react and Framer-Motion.",
    image: '/images/music-app.png',
    tags: ['React', 'JavaScript', 'Tailwind', 'Framer-Motion'],
    source: 'https://github.com/BhumilModi/Music-App',
    visit: 'https://music-app-bhumil.vercel.app/',
    id: 3,
  },
  {
    title: 'Twiiter-Web3-clone',
    description: "It is static frontend clone of twitter app , made with metamask authenification.",
    image: '/images/twitter.png',
    tags: ['React', 'JavaScript', 'Next.js', 'Tailwind', 'Metamask'],
    source: 'https://github.com/BhumilModi/Twitter-clone-web3.0',
    visit: 'https://twitter-clone-web3-0.vercel.app/',
    id: 4,
  },
  {
    title: 'GPT3-Clone',
    description: "This is a static website made wiht the help of a Figma design , made as a practice to learn React.",
    image: '/images/gpt3-clone.png',
    tags: ['React', 'JavaScript', 'CSS3'],
    source: 'https://github.com/BhumilModi/GPT3-clone',
    visit: 'https://gpt3-clone.vercel.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started My Journey as CSE student.', },
  { year: 2020, text: 'Got introduced to Front-end Development as a College project', },
  { year: 2021, text: 'Started Learning Deep Concepts of Front-End Development', },
  { year: 2022, text: 'Started Working on some Real Projects as a Front-End Developer', },
];